print("ALTISEC TECHNOLOGIES")
print("SKYHIGH CASB")
print("ABCD")
#These are testinmg done in UAT
print("commit")
print("VARONIS,PRISMA,CASB")
print("ALTISEC TECH")
print("BLA BLA BLA")
print("Monday")
print("ABCD")